### ISSUE TITLE
enemyspawner new bug

### ISSUE THREAD

**Issue by siurana-lin** [TitaniumTurbine/LethalCompanyMod#3]
After updating to version 1.0.1, I found that my spaceship couldn't land properly after joining other people's games, and it stopped loading seeds. When I was the host, it was normal on the first day, but it still happened the next day.

**Comment by tom-broadbent** [comment]
Is everyone on the server definitely using v1.0.1? Have you tried in singleplayer? What is your mod list?

**Comment by siurana-lin** [comment]
no，just me，single is ok,my mod list: 018d8335-d58d-3cb9-3862-b756a5e71fe4

**Comment by tom-broadbent** [comment]
Make sure that all players are using the mod and have the latest version. I haven't actually had the chance to test the mod in multiplayer yet, so please let me know if it works.

**Comment by siurana-lin** [comment]
I think this is just a mod suitable for the host. If it must be used by everyone, then I won't consider placing it on my mod list anymore. This would be a huge loss for me to create a public multiplayer that can be accessed by other unfamiliar players

**Comment by CoolLKKPS** [comment]
so... yea but in my opinion, if im doing modpack, i will use this mod, if playing on vanilla, i will go to use MoreMonster, simple
i choose this mod bc i want this mod spawn more modded monster instead just vanilla monster, think more different, so i will give this mod a big thumbs up

**Comment by CoolLKKPS** [comment]
but yea if also support vanilla, great that's awesome, so keep going @TitaniumTurbine , my modpack is count on u now >:)

Edit: u might be need to ask Lethal LevelLoader mod devs, they also have this issues previously, but after starting support Lethal Expansion they fixed this issues, so might be u have to

**Comment by CoolLKKPS** [comment]
https://github.com/IAmBatby/LethalLevelLoader/issues/19

**Comment by tom-broadbent** [comment]
I've just released version 1.0.2. TLDR - The mod now works properly but unfortunately is not compatible with vanilla clients. All players need the mod.

I've purchased a second copy of the game to help me test multiplayer, and it turned out that multiplayer did not function at all. 

The issue raised here was fixed by adding a check to ensure that the player was the host before trying to spawn enemies. This then revealed that enemies were unable to damage client players if they were in the wrong area (i.e. inside enemies being spawned outside). This is because the vanilla game has no way of telling the client players whether or not an enemy is outside. This is hard-coded into the enemy types. The game checks if a player and an enemy are in the same area before allowing damage, and damage is done on client side, so clients must know which area an enemy is in.

There were a few different options for fixing this issue. To make it compatible with vanilla clients, I would have to update each individual enemy ai class to move the dealing of damage to the server-side. This is messy and removes compatibility with modded enemies. Maybe in the future I'll add this method as a config option.

Another solution would be to write my own netcode to tell clients if an enemy is outside. This is probably the best solution but was taking too much time to figure out.

Instead, I've just overridden the check to see if an enemy and the player are in the same area. This is simple and it works but has the possibility to have minor effects on the ai behaviour and also requires all players to have the mod. This should be fine but I'll continue working on a better solution.
